# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  create:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: write
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: install libusb
        run: sudo apt update && sudo apt install -y libusb-1.0-0-dev

      - name: Build Release
        run: go build -v -o go-bsb-cams-${{ github.ref_name }} -ldflags "-X main.gitVersion=${{ github.ref_name }}" ./...
        if: github.ref_type == 'tag'

      - name: Build Non-Release
        run: go build ./...
        if: github.ref_type != 'tag'

      - name: Release Binary
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: go-bsb-cams-v*
